In [4]:
import pandas as pd
import numpy as np #use number matrices
import matplotlib.pyplot as plt
import tensorflow as tf

In [38]:
#step ! - Load Data
dataframe = pd.read_csv('data.csv')
#remove features we dont care about
dataframe = dataframe.drop(['index', 'price', 'sq_price'],axis=1)

#First 10 rows
dataframe = dataframe[0:10]
dataframe

      area  bathrooms
0   2104.0        3.0
1   1600.0        3.0
2   2400.0        3.0
3   1416.0        2.0
4   3000.0        4.0
5   1985.0        4.0
6   1534.0        3.0
7   1427.0        3.0
8   1380.0        3.0
9   1494.0        3.0
10  1940.0        4.0
11  2000.0        3.0
12  1890.0        3.0
13  4478.0        5.0
14  1268.0        3.0
15  2300.0        4.0
16  1320.0        2.0
17  1236.0        3.0
18  2609.0        4.0
19  3031.0        4.0
20  1767.0        3.0
21  1888.0        2.0
22  1604.0        3.0
23  1962.0        4.0
24  3890.0        3.0
25  1100.0        3.0
26  1458.0        3.0
27  2526.0        3.0
28  2200.0        3.0
29  2637.0        3.0
30  1839.0        2.0
31  1000.0        1.0
32  2040.0        4.0
33  3137.0        3.0
34  1811.0        4.0
35  1437.0        3.0
36  1239.0        3.0
37  2132.0        4.0
38  4215.0        4.0
39  2162.0        4.0

In [40]:
#step 2 - add labels
#1 is good, 0 is bad
dataframe.loc[:, ('y1')] = [1,1,1,0,0,1,0,1,1,1]
#y2 is the opposite of y1
dataframe.loc[:, ('y2')] = dataframe['y1'] == 0
#print TRUE/FALSE values to 1s and 0s
dataframe.loc[:, ('y2')] = dataframe['y2'].astype(int)
dataframe

      area  bathrooms  y1  y2
0   2104.0        3.0   1   0
1   1600.0        3.0   1   0
2   2400.0        3.0   1   0
3   1416.0        2.0   0   1
4   3000.0        4.0   0   1
5   1985.0        4.0   1   0
6   1534.0        3.0   0   1
7   1427.0        3.0   1   0
8   1380.0        3.0   1   0
9   1494.0        3.0   1   0
10  1940.0        4.0   1   0
11  2000.0        3.0   1   0
12  1890.0        3.0   1   0
13  4478.0        5.0   0   1
14  1268.0        3.0   0   1
15  2300.0        4.0   1   0
16  1320.0        2.0   0   1
17  1236.0        3.0   1   0
18  2609.0        4.0   1   0
19  3031.0        4.0   1   0
20  1767.0        3.0   0   1
21  1888.0        2.0   0   1
22  1604.0        3.0   0   1
23  1962.0        4.0   0   1
24  3890.0        3.0   0   1
25  1100.0        3.0   0   1
26  1458.0        3.0   0   1
27  2526.0        3.0   0   1
28  2200.0        3.0   0   1
29  2637.0        3.0   0   1
30  1839.0        2.0   0   1
31  1000.0        1.0   1   0
32  2040.0        4.0   1   0
33  3137.0        3.0   1   0
34  1811.0        4.0   0   1
35  1437.0        3.0   0   1
36  1239.0        3.0   1   0
37  2132.0        4.0   0   1
38  4215.0        4.0   1   0
39  2162.0        4.0   1   0

In [41]:
#Step 3 - prepare data for tensorflow
#tensors are generic versions of vectors and matrices
#vector - list of numbers (1D tensor)
#matrix - list of list of numbers (2D Tensor)

#convert features into input tensors
inputX = dataframe.loc[:, ['area', 'bathrooms']].as_matrix()
#convert labels to input tensorx
inputY = dataframe.loc[:, ['y1', 'y2']].as_matrix()
inputX

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00],
       [  1.94000000e+03,   4.00000000e+00],
       [  2.00000000e+03,   3.00000000e+00],
       [  1.89000000e+03,   3.00000000e+00],
       [  4.47800000e+03,   5.00000000e+00],
       [  1.26800000e+03,   3.00000000e+00],
       [  2.30000000e+03,   4.00000000e+00],
       [  1.32000000e+03,   2.00000000e+00],
       [  1.23600000e+03,   3.00000000e+00],
       [  2.60900000e+03,   4.00000000e+00],
       [  3.03100000e+03,   4.00000000e+00],
       [  1.76700000e+03,   3.00000000e+00],
       [  1.88800000e+03,   2.00000000e+00],
       [  1.60400000e+03,   3.00000000e+00],
       [  1.96200000e+03,   4.00000000e+00],
       [  3.89000000e+03,   3.00000000e+00],
       [  1.10000000e+03,   3.00000000e+00],
       [  1.45800000e+03,   3.00000000e+00],
       [  2.52600000e+03,   3.00000000e+00],
       [  2.20000000e+03,   3.00000000e+00],
       [  2.63700000e+03,   3.00000000e+00],
       [  1.83900000e+03,   2.00000000e+00],
       [  1.00000000e+03,   1.00000000e+00],
       [  2.04000000e+03,   4.00000000e+00],
       [  3.13700000e+03,   3.00000000e+00],
       [  1.81100000e+03,   4.00000000e+00],
       [  1.43700000e+03,   3.00000000e+00],
       [  1.23900000e+03,   3.00000000e+00],
       [  2.13200000e+03,   4.00000000e+00],
       [  4.21500000e+03,   4.00000000e+00],
       [  2.16200000e+03,   4.00000000e+00]])

In [42]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0]])

In [43]:
#step 4 - write out our hyperparameters
#rate of convergence
learning_rate = 0.000001
#epoch - complete training cycle
training_epochs = 2000
display_step = 50
n_samples = inputY.size

In [44]:
#step 5 - create computation graph/neural network
#for feature input examples, none means any number of examples. 2 is number of features
#placeholders are gateways for data into computational graphs
x = tf.placeholder(tf.float32,[None, 2])

#create weights
#2x2 float matrix we'll keep updating through the training process
#variables in tf hold and update paameters in memory buffers containing tensors
W = tf.Variable(tf.zeros([2,2]))

#add biases eg b in y = mx + b
b = tf.Variable(tf.zeros([2]))

#multiply our weights by our inputs
#weights are how we govern data flows in our computational graph
#multiply input by weights and add biases
y_values = tf.add(tf.matmul(x, W), b)

#apply softmax to valus we created
#softmax is our activation function. normalizes our values
y = tf.nn.softmax(y_values)

#feed in a matrix of labels
y_ = tf.placeholder(tf.float32, [None, 2])

In [45]:
#Step 6 - perform training
#create our cost function (mean squared error)
#reduce sum computes the sum of elements across dimensions of a tensor
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2 * n_samples)

#Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [46]:
#initialize variables and tensorflow session
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py:175: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.

In [47]:
#training loop
for i in range(training_epochs):
    sess.run(optimizer, feed_dict={x:inputX, y_:inputY})
    
    #write logs
    if(i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x:inputX, y_:inputY})
        print "training step:", '%04d'%(i), "cost=", "{:9f}".format(cc)
        
print "Optimization Finished!"
training_cost = sess.run(cost, feed_dict={x:inputX, y_:inputY})
print "training cost=", training_cost, "w=", sess.run(W), "b=", sess.run(b), "\n"

training step: 0000 cost=  0.125000
training step: 0050 cost=  0.125000
training step: 0100 cost=  0.125000
training step: 0150 cost=  0.125000
training step: 0200 cost=  0.125000
training step: 0250 cost=  0.125000
training step: 0300 cost=  0.125000
training step: 0350 cost=  0.125000
training step: 0400 cost=  0.125000
training step: 0450 cost=  0.125000
training step: 0500 cost=  0.125000
training step: 0550 cost=  0.125000
training step: 0600 cost=  0.125000
training step: 0650 cost=  0.125000
training step: 0700 cost=  0.125000
training step: 0750 cost=  0.125000
training step: 0800 cost=  0.125000
training step: 0850 cost=  0.125000
training step: 0900 cost=  0.125000
training step: 0950 cost=  0.125000
training step: 1000 cost=  0.125000
training step: 1050 cost=  0.125000
training step: 1100 cost=  0.125000
training step: 1150 cost=  0.125000
training step: 1200 cost=  0.125000
training step: 1250 cost=  0.125000
training step: 1300 cost=  0.124999
training step: 1350 cost=  0.124999
training step: 1400 cost=  0.124999
training step: 1450 cost=  0.124999
training step: 1500 cost=  0.124999
training step: 1550 cost=  0.124999
training step: 1600 cost=  0.124999
training step: 1650 cost=  0.124999
training step: 1700 cost=  0.124999
training step: 1750 cost=  0.124999
training step: 1800 cost=  0.124999
training step: 1850 cost=  0.124999
training step: 1900 cost=  0.124999
training step: 1950 cost=  0.124999
Optimization Finished!
training cost= 0.124999 w= [[ -4.35049117e-07   4.34564242e-07]
 [  2.56858202e-05  -2.56858275e-05]] b= [  2.04226509e-07  -2.04227547e-07]

In [48]:
sess.run(y, feed_dict = {x:inputX})

array([[ 0.49958119,  0.50041878],
       [ 0.4996908 ,  0.50030923],
       [ 0.4995169 ,  0.50048316],
       [ 0.49971792,  0.50028205],
       [ 0.4993993 ,  0.50060076],
       [ 0.49961996,  0.5003801 ],
       [ 0.49970514,  0.50029486],
       [ 0.49972835,  0.50027156],
       [ 0.4997386 ,  0.50026137],
       [ 0.49971381,  0.50028616],
       [ 0.49962977,  0.50037032],
       [ 0.49960384,  0.50039619],
       [ 0.49962777,  0.50037229],
       [ 0.49909076,  0.50090921],
       [ 0.49976295,  0.50023705],
       [ 0.49955148,  0.50044858],
       [ 0.49973881,  0.50026119],
       [ 0.49976993,  0.50023007],
       [ 0.49948424,  0.5005157 ],
       [ 0.49939254,  0.50060749],
       [ 0.4996545 ,  0.50034553],
       [ 0.49961534,  0.50038469],
       [ 0.49968991,  0.50031006],
       [ 0.49962494,  0.50037509],
       [ 0.49919292,  0.50080705],
       [ 0.49979949,  0.50020051],
       [ 0.49972168,  0.50027835],
       [ 0.49948946,  0.50051051],
       [ 0.49956033,  0.50043964],
       [ 0.49946535,  0.50053465],
       [ 0.49962598,  0.50037402],
       [ 0.49979553,  0.50020444],
       [ 0.49960795,  0.50039202],
       [ 0.49935666,  0.50064337],
       [ 0.49965775,  0.50034225],
       [ 0.49972627,  0.50027382],
       [ 0.49976927,  0.50023073],
       [ 0.49958798,  0.50041205],
       [ 0.49913511,  0.50086486],
       [ 0.49958146,  0.50041854]], dtype=float32)

In [ ]:
#basically all houses are good buys, 7/10
#How to improve? add a hidden layer